# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created

name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Publish to NPM
        uses: borales/actions-yarn@v4
        with:
          cmd: publish    
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
